/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZonesRouteImport } from './routes/zones'
import { Route as ZoneBrainRouteImport } from './routes/zone-brain'
import { Route as VisitWarRouteImport } from './routes/visit-war'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as TodayRouteImport } from './routes/today'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SequencesRouteImport } from './routes/sequences'
import { Route as RevivalRouteImport } from './routes/revival'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as PropertyOwnerRouteImport } from './routes/property-owner'
import { Route as PropertyHubRouteImport } from './routes/property-hub'
import { Route as OwnerBookingsRouteImport } from './routes/owner-bookings'
import { Route as MyTasksRouteImport } from './routes/my-tasks'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveLeadsRouteImport } from './routes/live-leads'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HeatmapRouteImport } from './routes/heatmap'
import { Route as HealthRouteImport } from './routes/health'
import { Route as HandoffsRouteImport } from './routes/handoffs'
import { Route as FollowUpsRouteImport } from './routes/follow-ups'
import { Route as ExecutionRouteImport } from './routes/execution'
import { Route as DailyProgressRouteImport } from './routes/daily-progress'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupplyHubIndexRouteImport } from './routes/supply-hub/index'
import { Route as MytIndexRouteImport } from './routes/myt/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SupplyHubMatchRouteImport } from './routes/supply-hub/match'
import { Route as SupplyHubAreasRouteImport } from './routes/supply-hub/areas'
import { Route as SupplyHubIdRouteImport } from './routes/supply-hub/$id'
import { Route as PropertyOwnerVisitsRouteImport } from './routes/property-owner.visits'
import { Route as PropertyOwnerPropertiesRouteImport } from './routes/property-owner.properties'
import { Route as PropertyOwnerProfileRouteImport } from './routes/property-owner.profile'
import { Route as PropertyOwnerNotificationsRouteImport } from './routes/property-owner.notifications'
import { Route as PropertyOwnerInventoryRouteImport } from './routes/property-owner.inventory'
import { Route as PropertyOwnerDashboardRouteImport } from './routes/property-owner.dashboard'
import { Route as PropertyOwnerBookingsRouteImport } from './routes/property-owner.bookings'
import { Route as PropertyOwnerApprovalsRouteImport } from './routes/property-owner.approvals'
import { Route as MytZonesRouteImport } from './routes/myt/zones'
import { Route as MytWarRoomRouteImport } from './routes/myt/war-room'
import { Route as MytToursRouteImport } from './routes/myt/tours'
import { Route as MytTeamRouteImport } from './routes/myt/team'
import { Route as MytTcmRouteImport } from './routes/myt/tcm'
import { Route as MytSettingsRouteImport } from './routes/myt/settings'
import { Route as MytScoreRouteImport } from './routes/myt/score'
import { Route as MytScheduleRouteImport } from './routes/myt/schedule'
import { Route as MytPropertiesRouteImport } from './routes/myt/properties'
import { Route as MytPostToursRouteImport } from './routes/myt/post-tours'
import { Route as MytOwnersCompareRouteImport } from './routes/myt/owners-compare'
import { Route as MytMismatchRouteImport } from './routes/myt/mismatch'
import { Route as MytMarketplaceRouteImport } from './routes/myt/marketplace'
import { Route as MytLeadsRouteImport } from './routes/myt/leads'
import { Route as MytLeaderboardRouteImport } from './routes/myt/leaderboard'
import { Route as MytInventoryFeedbackRouteImport } from './routes/myt/inventory-feedback'
import { Route as MytFunnelRouteImport } from './routes/myt/funnel'
import { Route as MytFlowOpsRouteImport } from './routes/myt/flow-ops'
import { Route as MytDraftsRouteImport } from './routes/myt/drafts'
import { Route as MytCalendarRouteImport } from './routes/myt/calendar'
import { Route as MytBookingsRouteImport } from './routes/myt/bookings'
import { Route as LeadsAddRouteImport } from './routes/leads.add'
import { Route as AdminWhatsappRouteImport } from './routes/admin.whatsapp'
import { Route as AdminWarroomRouteImport } from './routes/admin.warroom'
import { Route as AdminTenantsRouteImport } from './routes/admin.tenants'
import { Route as AdminSupremeRouteImport } from './routes/admin.supreme'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRevenueRouteImport } from './routes/admin.revenue'
import { Route as AdminRentsRouteImport } from './routes/admin.rents'
import { Route as AdminRadarRouteImport } from './routes/admin.radar'
import { Route as AdminPropertyGalleryRouteImport } from './routes/admin.property-gallery'
import { Route as AdminPropertyRouteImport } from './routes/admin.property'
import { Route as AdminPerformanceRouteImport } from './routes/admin.performance'
import { Route as AdminPeople360RouteImport } from './routes/admin.people360'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminOwnersRouteImport } from './routes/admin.owners'
import { Route as AdminOwnerBookingsRouteImport } from './routes/admin.owner-bookings'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminLeaderboardRouteImport } from './routes/admin.leaderboard'
import { Route as AdminIntelligenceRouteImport } from './routes/admin.intelligence'
import { Route as AdminImpactCommandRouteImport } from './routes/admin.impact-command'
import { Route as AdminImpactRouteImport } from './routes/admin.impact'
import { Route as AdminHealthScoreRouteImport } from './routes/admin.health-score'
import { Route as AdminExportsRouteImport } from './routes/admin.exports'
import { Route as AdminExecutionReportRouteImport } from './routes/admin.execution-report'
import { Route as AdminCommandRouteImport } from './routes/admin.command'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAgreementsRouteImport } from './routes/admin.agreements'
import { Route as PropertyOwnerPropertiesNewRouteImport } from './routes/property-owner.properties.new'
import { Route as MytTourIdRouteImport } from './routes/myt/tour.$id'
import { Route as MytTcmPerformanceRouteImport } from './routes/myt/tcm.performance'
import { Route as MytTcmActionsRouteImport } from './routes/myt/tcm.actions'
import { Route as MytFeedbackIdRouteImport } from './routes/myt/feedback.$id'
import { Route as AdminTenantsIdRouteImport } from './routes/admin.tenants.$id'
import { Route as AdminPropertyGalleryIdRouteImport } from './routes/admin.property-gallery.$id'
import { Route as AdminAgreementsIdRouteImport } from './routes/admin.agreements.$id'
import { Route as PropertyOwnerPropertiesIdRoomsRouteImport } from './routes/property-owner.properties.$id.rooms'
import { Route as MytTourIdReportRouteImport } from './routes/myt/tour.$id.report'
import { Route as AdminPerformanceTcmUserIdRouteImport } from './routes/admin.performance.tcm.$userId'
import { Route as AdminPerformancePropertyownerUserIdRouteImport } from './routes/admin.performance.propertyowner.$userId'
import { Route as AdminPerformanceFlowopsUserIdRouteImport } from './routes/admin.performance.flowops.$userId'
import { Route as PropertyOwnerPropertiesIdRoomsRoomIdRouteImport } from './routes/property-owner.properties.$id.rooms.$roomId'

const ZonesRoute = ZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => rootRouteImport,
} as any)
const ZoneBrainRoute = ZoneBrainRouteImport.update({
  id: '/zone-brain',
  path: '/zone-brain',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitWarRoute = VisitWarRouteImport.update({
  id: '/visit-war',
  path: '/visit-war',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SequencesRoute = SequencesRouteImport.update({
  id: '/sequences',
  path: '/sequences',
  getParentRoute: () => rootRouteImport,
} as any)
const RevivalRoute = RevivalRouteImport.update({
  id: '/revival',
  path: '/revival',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyOwnerRoute = PropertyOwnerRouteImport.update({
  id: '/property-owner',
  path: '/property-owner',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyHubRoute = PropertyHubRouteImport.update({
  id: '/property-hub',
  path: '/property-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerBookingsRoute = OwnerBookingsRouteImport.update({
  id: '/owner-bookings',
  path: '/owner-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTasksRoute = MyTasksRouteImport.update({
  id: '/my-tasks',
  path: '/my-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveLeadsRoute = LiveLeadsRouteImport.update({
  id: '/live-leads',
  path: '/live-leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatmapRoute = HeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffsRoute = HandoffsRouteImport.update({
  id: '/handoffs',
  path: '/handoffs',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpsRoute = FollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionRoute = ExecutionRouteImport.update({
  id: '/execution',
  path: '/execution',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyProgressRoute = DailyProgressRouteImport.update({
  id: '/daily-progress',
  path: '/daily-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplyHubIndexRoute = SupplyHubIndexRouteImport.update({
  id: '/supply-hub/',
  path: '/supply-hub/',
  getParentRoute: () => rootRouteImport,
} as any)
const MytIndexRoute = MytIndexRouteImport.update({
  id: '/myt/',
  path: '/myt/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SupplyHubMatchRoute = SupplyHubMatchRouteImport.update({
  id: '/supply-hub/match',
  path: '/supply-hub/match',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplyHubAreasRoute = SupplyHubAreasRouteImport.update({
  id: '/supply-hub/areas',
  path: '/supply-hub/areas',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplyHubIdRoute = SupplyHubIdRouteImport.update({
  id: '/supply-hub/$id',
  path: '/supply-hub/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyOwnerVisitsRoute = PropertyOwnerVisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => PropertyOwnerRoute,
} as any)
const PropertyOwnerPropertiesRoute = PropertyOwnerPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => PropertyOwnerRoute,
} as any)
const PropertyOwnerProfileRoute = PropertyOwnerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PropertyOwnerRoute,
} as any)
const PropertyOwnerNotificationsRoute =
  PropertyOwnerNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => PropertyOwnerRoute,
  } as any)
const PropertyOwnerInventoryRoute = PropertyOwnerInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => PropertyOwnerRoute,
} as any)
const PropertyOwnerDashboardRoute = PropertyOwnerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PropertyOwnerRoute,
} as any)
const PropertyOwnerBookingsRoute = PropertyOwnerBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => PropertyOwnerRoute,
} as any)
const PropertyOwnerApprovalsRoute = PropertyOwnerApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => PropertyOwnerRoute,
} as any)
const MytZonesRoute = MytZonesRouteImport.update({
  id: '/myt/zones',
  path: '/myt/zones',
  getParentRoute: () => rootRouteImport,
} as any)
const MytWarRoomRoute = MytWarRoomRouteImport.update({
  id: '/myt/war-room',
  path: '/myt/war-room',
  getParentRoute: () => rootRouteImport,
} as any)
const MytToursRoute = MytToursRouteImport.update({
  id: '/myt/tours',
  path: '/myt/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const MytTeamRoute = MytTeamRouteImport.update({
  id: '/myt/team',
  path: '/myt/team',
  getParentRoute: () => rootRouteImport,
} as any)
const MytTcmRoute = MytTcmRouteImport.update({
  id: '/myt/tcm',
  path: '/myt/tcm',
  getParentRoute: () => rootRouteImport,
} as any)
const MytSettingsRoute = MytSettingsRouteImport.update({
  id: '/myt/settings',
  path: '/myt/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MytScoreRoute = MytScoreRouteImport.update({
  id: '/myt/score',
  path: '/myt/score',
  getParentRoute: () => rootRouteImport,
} as any)
const MytScheduleRoute = MytScheduleRouteImport.update({
  id: '/myt/schedule',
  path: '/myt/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const MytPropertiesRoute = MytPropertiesRouteImport.update({
  id: '/myt/properties',
  path: '/myt/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const MytPostToursRoute = MytPostToursRouteImport.update({
  id: '/myt/post-tours',
  path: '/myt/post-tours',
  getParentRoute: () => rootRouteImport,
} as any)
const MytOwnersCompareRoute = MytOwnersCompareRouteImport.update({
  id: '/myt/owners-compare',
  path: '/myt/owners-compare',
  getParentRoute: () => rootRouteImport,
} as any)
const MytMismatchRoute = MytMismatchRouteImport.update({
  id: '/myt/mismatch',
  path: '/myt/mismatch',
  getParentRoute: () => rootRouteImport,
} as any)
const MytMarketplaceRoute = MytMarketplaceRouteImport.update({
  id: '/myt/marketplace',
  path: '/myt/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MytLeadsRoute = MytLeadsRouteImport.update({
  id: '/myt/leads',
  path: '/myt/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const MytLeaderboardRoute = MytLeaderboardRouteImport.update({
  id: '/myt/leaderboard',
  path: '/myt/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MytInventoryFeedbackRoute = MytInventoryFeedbackRouteImport.update({
  id: '/myt/inventory-feedback',
  path: '/myt/inventory-feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const MytFunnelRoute = MytFunnelRouteImport.update({
  id: '/myt/funnel',
  path: '/myt/funnel',
  getParentRoute: () => rootRouteImport,
} as any)
const MytFlowOpsRoute = MytFlowOpsRouteImport.update({
  id: '/myt/flow-ops',
  path: '/myt/flow-ops',
  getParentRoute: () => rootRouteImport,
} as any)
const MytDraftsRoute = MytDraftsRouteImport.update({
  id: '/myt/drafts',
  path: '/myt/drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const MytCalendarRoute = MytCalendarRouteImport.update({
  id: '/myt/calendar',
  path: '/myt/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const MytBookingsRoute = MytBookingsRouteImport.update({
  id: '/myt/bookings',
  path: '/myt/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsAddRoute = LeadsAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => LeadsRoute,
} as any)
const AdminWhatsappRoute = AdminWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWarroomRoute = AdminWarroomRouteImport.update({
  id: '/warroom',
  path: '/warroom',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupremeRoute = AdminSupremeRouteImport.update({
  id: '/supreme',
  path: '/supreme',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRentsRoute = AdminRentsRouteImport.update({
  id: '/rents',
  path: '/rents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRadarRoute = AdminRadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPropertyGalleryRoute = AdminPropertyGalleryRouteImport.update({
  id: '/property-gallery',
  path: '/property-gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPropertyRoute = AdminPropertyRouteImport.update({
  id: '/property',
  path: '/property',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPerformanceRoute = AdminPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPeople360Route = AdminPeople360RouteImport.update({
  id: '/people360',
  path: '/people360',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOwnersRoute = AdminOwnersRouteImport.update({
  id: '/owners',
  path: '/owners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOwnerBookingsRoute = AdminOwnerBookingsRouteImport.update({
  id: '/owner-bookings',
  path: '/owner-bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeaderboardRoute = AdminLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntelligenceRoute = AdminIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImpactCommandRoute = AdminImpactCommandRouteImport.update({
  id: '/impact-command',
  path: '/impact-command',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImpactRoute = AdminImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHealthScoreRoute = AdminHealthScoreRouteImport.update({
  id: '/health-score',
  path: '/health-score',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExportsRoute = AdminExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExecutionReportRoute = AdminExecutionReportRouteImport.update({
  id: '/execution-report',
  path: '/execution-report',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommandRoute = AdminCommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgreementsRoute = AdminAgreementsRouteImport.update({
  id: '/agreements',
  path: '/agreements',
  getParentRoute: () => AdminRoute,
} as any)
const PropertyOwnerPropertiesNewRoute =
  PropertyOwnerPropertiesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => PropertyOwnerPropertiesRoute,
  } as any)
const MytTourIdRoute = MytTourIdRouteImport.update({
  id: '/myt/tour/$id',
  path: '/myt/tour/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MytTcmPerformanceRoute = MytTcmPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => MytTcmRoute,
} as any)
const MytTcmActionsRoute = MytTcmActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => MytTcmRoute,
} as any)
const MytFeedbackIdRoute = MytFeedbackIdRouteImport.update({
  id: '/myt/feedback/$id',
  path: '/myt/feedback/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTenantsIdRoute = AdminTenantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminTenantsRoute,
} as any)
const AdminPropertyGalleryIdRoute = AdminPropertyGalleryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPropertyGalleryRoute,
} as any)
const AdminAgreementsIdRoute = AdminAgreementsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAgreementsRoute,
} as any)
const PropertyOwnerPropertiesIdRoomsRoute =
  PropertyOwnerPropertiesIdRoomsRouteImport.update({
    id: '/$id/rooms',
    path: '/$id/rooms',
    getParentRoute: () => PropertyOwnerPropertiesRoute,
  } as any)
const MytTourIdReportRoute = MytTourIdReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => MytTourIdRoute,
} as any)
const AdminPerformanceTcmUserIdRoute =
  AdminPerformanceTcmUserIdRouteImport.update({
    id: '/tcm/$userId',
    path: '/tcm/$userId',
    getParentRoute: () => AdminPerformanceRoute,
  } as any)
const AdminPerformancePropertyownerUserIdRoute =
  AdminPerformancePropertyownerUserIdRouteImport.update({
    id: '/propertyowner/$userId',
    path: '/propertyowner/$userId',
    getParentRoute: () => AdminPerformanceRoute,
  } as any)
const AdminPerformanceFlowopsUserIdRoute =
  AdminPerformanceFlowopsUserIdRouteImport.update({
    id: '/flowops/$userId',
    path: '/flowops/$userId',
    getParentRoute: () => AdminPerformanceRoute,
  } as any)
const PropertyOwnerPropertiesIdRoomsRoomIdRoute =
  PropertyOwnerPropertiesIdRoomsRoomIdRouteImport.update({
    id: '/$roomId',
    path: '/$roomId',
    getParentRoute: () => PropertyOwnerPropertiesIdRoomsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/coach': typeof CoachRoute
  '/daily-progress': typeof DailyProgressRoute
  '/execution': typeof ExecutionRoute
  '/follow-ups': typeof FollowUpsRoute
  '/handoffs': typeof HandoffsRoute
  '/health': typeof HealthRoute
  '/heatmap': typeof HeatmapRoute
  '/help': typeof HelpRoute
  '/impact': typeof ImpactRoute
  '/inbox': typeof InboxRoute
  '/inventory': typeof InventoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/leads': typeof LeadsRouteWithChildren
  '/live-leads': typeof LiveLeadsRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/my-tasks': typeof MyTasksRoute
  '/owner-bookings': typeof OwnerBookingsRoute
  '/property-hub': typeof PropertyHubRoute
  '/property-owner': typeof PropertyOwnerRouteWithChildren
  '/queue': typeof QueueRoute
  '/revenue': typeof RevenueRoute
  '/revival': typeof RevivalRoute
  '/sequences': typeof SequencesRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
  '/tours': typeof ToursRoute
  '/visit-war': typeof VisitWarRoute
  '/zone-brain': typeof ZoneBrainRoute
  '/zones': typeof ZonesRoute
  '/admin/agreements': typeof AdminAgreementsRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/command': typeof AdminCommandRoute
  '/admin/execution-report': typeof AdminExecutionReportRoute
  '/admin/exports': typeof AdminExportsRoute
  '/admin/health-score': typeof AdminHealthScoreRoute
  '/admin/impact': typeof AdminImpactRoute
  '/admin/impact-command': typeof AdminImpactCommandRoute
  '/admin/intelligence': typeof AdminIntelligenceRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/owner-bookings': typeof AdminOwnerBookingsRoute
  '/admin/owners': typeof AdminOwnersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/people360': typeof AdminPeople360Route
  '/admin/performance': typeof AdminPerformanceRouteWithChildren
  '/admin/property': typeof AdminPropertyRoute
  '/admin/property-gallery': typeof AdminPropertyGalleryRouteWithChildren
  '/admin/radar': typeof AdminRadarRoute
  '/admin/rents': typeof AdminRentsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/supreme': typeof AdminSupremeRoute
  '/admin/tenants': typeof AdminTenantsRouteWithChildren
  '/admin/warroom': typeof AdminWarroomRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/leads/add': typeof LeadsAddRoute
  '/myt/bookings': typeof MytBookingsRoute
  '/myt/calendar': typeof MytCalendarRoute
  '/myt/drafts': typeof MytDraftsRoute
  '/myt/flow-ops': typeof MytFlowOpsRoute
  '/myt/funnel': typeof MytFunnelRoute
  '/myt/inventory-feedback': typeof MytInventoryFeedbackRoute
  '/myt/leaderboard': typeof MytLeaderboardRoute
  '/myt/leads': typeof MytLeadsRoute
  '/myt/marketplace': typeof MytMarketplaceRoute
  '/myt/mismatch': typeof MytMismatchRoute
  '/myt/owners-compare': typeof MytOwnersCompareRoute
  '/myt/post-tours': typeof MytPostToursRoute
  '/myt/properties': typeof MytPropertiesRoute
  '/myt/schedule': typeof MytScheduleRoute
  '/myt/score': typeof MytScoreRoute
  '/myt/settings': typeof MytSettingsRoute
  '/myt/tcm': typeof MytTcmRouteWithChildren
  '/myt/team': typeof MytTeamRoute
  '/myt/tours': typeof MytToursRoute
  '/myt/war-room': typeof MytWarRoomRoute
  '/myt/zones': typeof MytZonesRoute
  '/property-owner/approvals': typeof PropertyOwnerApprovalsRoute
  '/property-owner/bookings': typeof PropertyOwnerBookingsRoute
  '/property-owner/dashboard': typeof PropertyOwnerDashboardRoute
  '/property-owner/inventory': typeof PropertyOwnerInventoryRoute
  '/property-owner/notifications': typeof PropertyOwnerNotificationsRoute
  '/property-owner/profile': typeof PropertyOwnerProfileRoute
  '/property-owner/properties': typeof PropertyOwnerPropertiesRouteWithChildren
  '/property-owner/visits': typeof PropertyOwnerVisitsRoute
  '/supply-hub/$id': typeof SupplyHubIdRoute
  '/supply-hub/areas': typeof SupplyHubAreasRoute
  '/supply-hub/match': typeof SupplyHubMatchRoute
  '/admin/': typeof AdminIndexRoute
  '/myt/': typeof MytIndexRoute
  '/supply-hub/': typeof SupplyHubIndexRoute
  '/admin/agreements/$id': typeof AdminAgreementsIdRoute
  '/admin/property-gallery/$id': typeof AdminPropertyGalleryIdRoute
  '/admin/tenants/$id': typeof AdminTenantsIdRoute
  '/myt/feedback/$id': typeof MytFeedbackIdRoute
  '/myt/tcm/actions': typeof MytTcmActionsRoute
  '/myt/tcm/performance': typeof MytTcmPerformanceRoute
  '/myt/tour/$id': typeof MytTourIdRouteWithChildren
  '/property-owner/properties/new': typeof PropertyOwnerPropertiesNewRoute
  '/admin/performance/flowops/$userId': typeof AdminPerformanceFlowopsUserIdRoute
  '/admin/performance/propertyowner/$userId': typeof AdminPerformancePropertyownerUserIdRoute
  '/admin/performance/tcm/$userId': typeof AdminPerformanceTcmUserIdRoute
  '/myt/tour/$id/report': typeof MytTourIdReportRoute
  '/property-owner/properties/$id/rooms': typeof PropertyOwnerPropertiesIdRoomsRouteWithChildren
  '/property-owner/properties/$id/rooms/$roomId': typeof PropertyOwnerPropertiesIdRoomsRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/calendar': typeof CalendarRoute
  '/coach': typeof CoachRoute
  '/daily-progress': typeof DailyProgressRoute
  '/execution': typeof ExecutionRoute
  '/follow-ups': typeof FollowUpsRoute
  '/handoffs': typeof HandoffsRoute
  '/health': typeof HealthRoute
  '/heatmap': typeof HeatmapRoute
  '/help': typeof HelpRoute
  '/impact': typeof ImpactRoute
  '/inbox': typeof InboxRoute
  '/inventory': typeof InventoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/leads': typeof LeadsRouteWithChildren
  '/live-leads': typeof LiveLeadsRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/my-tasks': typeof MyTasksRoute
  '/owner-bookings': typeof OwnerBookingsRoute
  '/property-hub': typeof PropertyHubRoute
  '/property-owner': typeof PropertyOwnerRouteWithChildren
  '/queue': typeof QueueRoute
  '/revenue': typeof RevenueRoute
  '/revival': typeof RevivalRoute
  '/sequences': typeof SequencesRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
  '/tours': typeof ToursRoute
  '/visit-war': typeof VisitWarRoute
  '/zone-brain': typeof ZoneBrainRoute
  '/zones': typeof ZonesRoute
  '/admin/agreements': typeof AdminAgreementsRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/command': typeof AdminCommandRoute
  '/admin/execution-report': typeof AdminExecutionReportRoute
  '/admin/exports': typeof AdminExportsRoute
  '/admin/health-score': typeof AdminHealthScoreRoute
  '/admin/impact': typeof AdminImpactRoute
  '/admin/impact-command': typeof AdminImpactCommandRoute
  '/admin/intelligence': typeof AdminIntelligenceRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/owner-bookings': typeof AdminOwnerBookingsRoute
  '/admin/owners': typeof AdminOwnersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/people360': typeof AdminPeople360Route
  '/admin/performance': typeof AdminPerformanceRouteWithChildren
  '/admin/property': typeof AdminPropertyRoute
  '/admin/property-gallery': typeof AdminPropertyGalleryRouteWithChildren
  '/admin/radar': typeof AdminRadarRoute
  '/admin/rents': typeof AdminRentsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/supreme': typeof AdminSupremeRoute
  '/admin/tenants': typeof AdminTenantsRouteWithChildren
  '/admin/warroom': typeof AdminWarroomRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/leads/add': typeof LeadsAddRoute
  '/myt/bookings': typeof MytBookingsRoute
  '/myt/calendar': typeof MytCalendarRoute
  '/myt/drafts': typeof MytDraftsRoute
  '/myt/flow-ops': typeof MytFlowOpsRoute
  '/myt/funnel': typeof MytFunnelRoute
  '/myt/inventory-feedback': typeof MytInventoryFeedbackRoute
  '/myt/leaderboard': typeof MytLeaderboardRoute
  '/myt/leads': typeof MytLeadsRoute
  '/myt/marketplace': typeof MytMarketplaceRoute
  '/myt/mismatch': typeof MytMismatchRoute
  '/myt/owners-compare': typeof MytOwnersCompareRoute
  '/myt/post-tours': typeof MytPostToursRoute
  '/myt/properties': typeof MytPropertiesRoute
  '/myt/schedule': typeof MytScheduleRoute
  '/myt/score': typeof MytScoreRoute
  '/myt/settings': typeof MytSettingsRoute
  '/myt/tcm': typeof MytTcmRouteWithChildren
  '/myt/team': typeof MytTeamRoute
  '/myt/tours': typeof MytToursRoute
  '/myt/war-room': typeof MytWarRoomRoute
  '/myt/zones': typeof MytZonesRoute
  '/property-owner/approvals': typeof PropertyOwnerApprovalsRoute
  '/property-owner/bookings': typeof PropertyOwnerBookingsRoute
  '/property-owner/dashboard': typeof PropertyOwnerDashboardRoute
  '/property-owner/inventory': typeof PropertyOwnerInventoryRoute
  '/property-owner/notifications': typeof PropertyOwnerNotificationsRoute
  '/property-owner/profile': typeof PropertyOwnerProfileRoute
  '/property-owner/properties': typeof PropertyOwnerPropertiesRouteWithChildren
  '/property-owner/visits': typeof PropertyOwnerVisitsRoute
  '/supply-hub/$id': typeof SupplyHubIdRoute
  '/supply-hub/areas': typeof SupplyHubAreasRoute
  '/supply-hub/match': typeof SupplyHubMatchRoute
  '/admin': typeof AdminIndexRoute
  '/myt': typeof MytIndexRoute
  '/supply-hub': typeof SupplyHubIndexRoute
  '/admin/agreements/$id': typeof AdminAgreementsIdRoute
  '/admin/property-gallery/$id': typeof AdminPropertyGalleryIdRoute
  '/admin/tenants/$id': typeof AdminTenantsIdRoute
  '/myt/feedback/$id': typeof MytFeedbackIdRoute
  '/myt/tcm/actions': typeof MytTcmActionsRoute
  '/myt/tcm/performance': typeof MytTcmPerformanceRoute
  '/myt/tour/$id': typeof MytTourIdRouteWithChildren
  '/property-owner/properties/new': typeof PropertyOwnerPropertiesNewRoute
  '/admin/performance/flowops/$userId': typeof AdminPerformanceFlowopsUserIdRoute
  '/admin/performance/propertyowner/$userId': typeof AdminPerformancePropertyownerUserIdRoute
  '/admin/performance/tcm/$userId': typeof AdminPerformanceTcmUserIdRoute
  '/myt/tour/$id/report': typeof MytTourIdReportRoute
  '/property-owner/properties/$id/rooms': typeof PropertyOwnerPropertiesIdRoomsRouteWithChildren
  '/property-owner/properties/$id/rooms/$roomId': typeof PropertyOwnerPropertiesIdRoomsRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/coach': typeof CoachRoute
  '/daily-progress': typeof DailyProgressRoute
  '/execution': typeof ExecutionRoute
  '/follow-ups': typeof FollowUpsRoute
  '/handoffs': typeof HandoffsRoute
  '/health': typeof HealthRoute
  '/heatmap': typeof HeatmapRoute
  '/help': typeof HelpRoute
  '/impact': typeof ImpactRoute
  '/inbox': typeof InboxRoute
  '/inventory': typeof InventoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/leads': typeof LeadsRouteWithChildren
  '/live-leads': typeof LiveLeadsRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/my-tasks': typeof MyTasksRoute
  '/owner-bookings': typeof OwnerBookingsRoute
  '/property-hub': typeof PropertyHubRoute
  '/property-owner': typeof PropertyOwnerRouteWithChildren
  '/queue': typeof QueueRoute
  '/revenue': typeof RevenueRoute
  '/revival': typeof RevivalRoute
  '/sequences': typeof SequencesRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
  '/tours': typeof ToursRoute
  '/visit-war': typeof VisitWarRoute
  '/zone-brain': typeof ZoneBrainRoute
  '/zones': typeof ZonesRoute
  '/admin/agreements': typeof AdminAgreementsRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/command': typeof AdminCommandRoute
  '/admin/execution-report': typeof AdminExecutionReportRoute
  '/admin/exports': typeof AdminExportsRoute
  '/admin/health-score': typeof AdminHealthScoreRoute
  '/admin/impact': typeof AdminImpactRoute
  '/admin/impact-command': typeof AdminImpactCommandRoute
  '/admin/intelligence': typeof AdminIntelligenceRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/owner-bookings': typeof AdminOwnerBookingsRoute
  '/admin/owners': typeof AdminOwnersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/people360': typeof AdminPeople360Route
  '/admin/performance': typeof AdminPerformanceRouteWithChildren
  '/admin/property': typeof AdminPropertyRoute
  '/admin/property-gallery': typeof AdminPropertyGalleryRouteWithChildren
  '/admin/radar': typeof AdminRadarRoute
  '/admin/rents': typeof AdminRentsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/supreme': typeof AdminSupremeRoute
  '/admin/tenants': typeof AdminTenantsRouteWithChildren
  '/admin/warroom': typeof AdminWarroomRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/leads/add': typeof LeadsAddRoute
  '/myt/bookings': typeof MytBookingsRoute
  '/myt/calendar': typeof MytCalendarRoute
  '/myt/drafts': typeof MytDraftsRoute
  '/myt/flow-ops': typeof MytFlowOpsRoute
  '/myt/funnel': typeof MytFunnelRoute
  '/myt/inventory-feedback': typeof MytInventoryFeedbackRoute
  '/myt/leaderboard': typeof MytLeaderboardRoute
  '/myt/leads': typeof MytLeadsRoute
  '/myt/marketplace': typeof MytMarketplaceRoute
  '/myt/mismatch': typeof MytMismatchRoute
  '/myt/owners-compare': typeof MytOwnersCompareRoute
  '/myt/post-tours': typeof MytPostToursRoute
  '/myt/properties': typeof MytPropertiesRoute
  '/myt/schedule': typeof MytScheduleRoute
  '/myt/score': typeof MytScoreRoute
  '/myt/settings': typeof MytSettingsRoute
  '/myt/tcm': typeof MytTcmRouteWithChildren
  '/myt/team': typeof MytTeamRoute
  '/myt/tours': typeof MytToursRoute
  '/myt/war-room': typeof MytWarRoomRoute
  '/myt/zones': typeof MytZonesRoute
  '/property-owner/approvals': typeof PropertyOwnerApprovalsRoute
  '/property-owner/bookings': typeof PropertyOwnerBookingsRoute
  '/property-owner/dashboard': typeof PropertyOwnerDashboardRoute
  '/property-owner/inventory': typeof PropertyOwnerInventoryRoute
  '/property-owner/notifications': typeof PropertyOwnerNotificationsRoute
  '/property-owner/profile': typeof PropertyOwnerProfileRoute
  '/property-owner/properties': typeof PropertyOwnerPropertiesRouteWithChildren
  '/property-owner/visits': typeof PropertyOwnerVisitsRoute
  '/supply-hub/$id': typeof SupplyHubIdRoute
  '/supply-hub/areas': typeof SupplyHubAreasRoute
  '/supply-hub/match': typeof SupplyHubMatchRoute
  '/admin/': typeof AdminIndexRoute
  '/myt/': typeof MytIndexRoute
  '/supply-hub/': typeof SupplyHubIndexRoute
  '/admin/agreements/$id': typeof AdminAgreementsIdRoute
  '/admin/property-gallery/$id': typeof AdminPropertyGalleryIdRoute
  '/admin/tenants/$id': typeof AdminTenantsIdRoute
  '/myt/feedback/$id': typeof MytFeedbackIdRoute
  '/myt/tcm/actions': typeof MytTcmActionsRoute
  '/myt/tcm/performance': typeof MytTcmPerformanceRoute
  '/myt/tour/$id': typeof MytTourIdRouteWithChildren
  '/property-owner/properties/new': typeof PropertyOwnerPropertiesNewRoute
  '/admin/performance/flowops/$userId': typeof AdminPerformanceFlowopsUserIdRoute
  '/admin/performance/propertyowner/$userId': typeof AdminPerformancePropertyownerUserIdRoute
  '/admin/performance/tcm/$userId': typeof AdminPerformanceTcmUserIdRoute
  '/myt/tour/$id/report': typeof MytTourIdReportRoute
  '/property-owner/properties/$id/rooms': typeof PropertyOwnerPropertiesIdRoomsRouteWithChildren
  '/property-owner/properties/$id/rooms/$roomId': typeof PropertyOwnerPropertiesIdRoomsRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/admin'
    | '/calendar'
    | '/coach'
    | '/daily-progress'
    | '/execution'
    | '/follow-ups'
    | '/handoffs'
    | '/health'
    | '/heatmap'
    | '/help'
    | '/impact'
    | '/inbox'
    | '/inventory'
    | '/leaderboard'
    | '/leads'
    | '/live-leads'
    | '/login'
    | '/manager'
    | '/my-tasks'
    | '/owner-bookings'
    | '/property-hub'
    | '/property-owner'
    | '/queue'
    | '/revenue'
    | '/revival'
    | '/sequences'
    | '/settings'
    | '/today'
    | '/tours'
    | '/visit-war'
    | '/zone-brain'
    | '/zones'
    | '/admin/agreements'
    | '/admin/audit'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/command'
    | '/admin/execution-report'
    | '/admin/exports'
    | '/admin/health-score'
    | '/admin/impact'
    | '/admin/impact-command'
    | '/admin/intelligence'
    | '/admin/leaderboard'
    | '/admin/leads'
    | '/admin/owner-bookings'
    | '/admin/owners'
    | '/admin/payouts'
    | '/admin/people360'
    | '/admin/performance'
    | '/admin/property'
    | '/admin/property-gallery'
    | '/admin/radar'
    | '/admin/rents'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/supreme'
    | '/admin/tenants'
    | '/admin/warroom'
    | '/admin/whatsapp'
    | '/leads/add'
    | '/myt/bookings'
    | '/myt/calendar'
    | '/myt/drafts'
    | '/myt/flow-ops'
    | '/myt/funnel'
    | '/myt/inventory-feedback'
    | '/myt/leaderboard'
    | '/myt/leads'
    | '/myt/marketplace'
    | '/myt/mismatch'
    | '/myt/owners-compare'
    | '/myt/post-tours'
    | '/myt/properties'
    | '/myt/schedule'
    | '/myt/score'
    | '/myt/settings'
    | '/myt/tcm'
    | '/myt/team'
    | '/myt/tours'
    | '/myt/war-room'
    | '/myt/zones'
    | '/property-owner/approvals'
    | '/property-owner/bookings'
    | '/property-owner/dashboard'
    | '/property-owner/inventory'
    | '/property-owner/notifications'
    | '/property-owner/profile'
    | '/property-owner/properties'
    | '/property-owner/visits'
    | '/supply-hub/$id'
    | '/supply-hub/areas'
    | '/supply-hub/match'
    | '/admin/'
    | '/myt/'
    | '/supply-hub/'
    | '/admin/agreements/$id'
    | '/admin/property-gallery/$id'
    | '/admin/tenants/$id'
    | '/myt/feedback/$id'
    | '/myt/tcm/actions'
    | '/myt/tcm/performance'
    | '/myt/tour/$id'
    | '/property-owner/properties/new'
    | '/admin/performance/flowops/$userId'
    | '/admin/performance/propertyowner/$userId'
    | '/admin/performance/tcm/$userId'
    | '/myt/tour/$id/report'
    | '/property-owner/properties/$id/rooms'
    | '/property-owner/properties/$id/rooms/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/calendar'
    | '/coach'
    | '/daily-progress'
    | '/execution'
    | '/follow-ups'
    | '/handoffs'
    | '/health'
    | '/heatmap'
    | '/help'
    | '/impact'
    | '/inbox'
    | '/inventory'
    | '/leaderboard'
    | '/leads'
    | '/live-leads'
    | '/login'
    | '/manager'
    | '/my-tasks'
    | '/owner-bookings'
    | '/property-hub'
    | '/property-owner'
    | '/queue'
    | '/revenue'
    | '/revival'
    | '/sequences'
    | '/settings'
    | '/today'
    | '/tours'
    | '/visit-war'
    | '/zone-brain'
    | '/zones'
    | '/admin/agreements'
    | '/admin/audit'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/command'
    | '/admin/execution-report'
    | '/admin/exports'
    | '/admin/health-score'
    | '/admin/impact'
    | '/admin/impact-command'
    | '/admin/intelligence'
    | '/admin/leaderboard'
    | '/admin/leads'
    | '/admin/owner-bookings'
    | '/admin/owners'
    | '/admin/payouts'
    | '/admin/people360'
    | '/admin/performance'
    | '/admin/property'
    | '/admin/property-gallery'
    | '/admin/radar'
    | '/admin/rents'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/supreme'
    | '/admin/tenants'
    | '/admin/warroom'
    | '/admin/whatsapp'
    | '/leads/add'
    | '/myt/bookings'
    | '/myt/calendar'
    | '/myt/drafts'
    | '/myt/flow-ops'
    | '/myt/funnel'
    | '/myt/inventory-feedback'
    | '/myt/leaderboard'
    | '/myt/leads'
    | '/myt/marketplace'
    | '/myt/mismatch'
    | '/myt/owners-compare'
    | '/myt/post-tours'
    | '/myt/properties'
    | '/myt/schedule'
    | '/myt/score'
    | '/myt/settings'
    | '/myt/tcm'
    | '/myt/team'
    | '/myt/tours'
    | '/myt/war-room'
    | '/myt/zones'
    | '/property-owner/approvals'
    | '/property-owner/bookings'
    | '/property-owner/dashboard'
    | '/property-owner/inventory'
    | '/property-owner/notifications'
    | '/property-owner/profile'
    | '/property-owner/properties'
    | '/property-owner/visits'
    | '/supply-hub/$id'
    | '/supply-hub/areas'
    | '/supply-hub/match'
    | '/admin'
    | '/myt'
    | '/supply-hub'
    | '/admin/agreements/$id'
    | '/admin/property-gallery/$id'
    | '/admin/tenants/$id'
    | '/myt/feedback/$id'
    | '/myt/tcm/actions'
    | '/myt/tcm/performance'
    | '/myt/tour/$id'
    | '/property-owner/properties/new'
    | '/admin/performance/flowops/$userId'
    | '/admin/performance/propertyowner/$userId'
    | '/admin/performance/tcm/$userId'
    | '/myt/tour/$id/report'
    | '/property-owner/properties/$id/rooms'
    | '/property-owner/properties/$id/rooms/$roomId'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/admin'
    | '/calendar'
    | '/coach'
    | '/daily-progress'
    | '/execution'
    | '/follow-ups'
    | '/handoffs'
    | '/health'
    | '/heatmap'
    | '/help'
    | '/impact'
    | '/inbox'
    | '/inventory'
    | '/leaderboard'
    | '/leads'
    | '/live-leads'
    | '/login'
    | '/manager'
    | '/my-tasks'
    | '/owner-bookings'
    | '/property-hub'
    | '/property-owner'
    | '/queue'
    | '/revenue'
    | '/revival'
    | '/sequences'
    | '/settings'
    | '/today'
    | '/tours'
    | '/visit-war'
    | '/zone-brain'
    | '/zones'
    | '/admin/agreements'
    | '/admin/audit'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/command'
    | '/admin/execution-report'
    | '/admin/exports'
    | '/admin/health-score'
    | '/admin/impact'
    | '/admin/impact-command'
    | '/admin/intelligence'
    | '/admin/leaderboard'
    | '/admin/leads'
    | '/admin/owner-bookings'
    | '/admin/owners'
    | '/admin/payouts'
    | '/admin/people360'
    | '/admin/performance'
    | '/admin/property'
    | '/admin/property-gallery'
    | '/admin/radar'
    | '/admin/rents'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/supreme'
    | '/admin/tenants'
    | '/admin/warroom'
    | '/admin/whatsapp'
    | '/leads/add'
    | '/myt/bookings'
    | '/myt/calendar'
    | '/myt/drafts'
    | '/myt/flow-ops'
    | '/myt/funnel'
    | '/myt/inventory-feedback'
    | '/myt/leaderboard'
    | '/myt/leads'
    | '/myt/marketplace'
    | '/myt/mismatch'
    | '/myt/owners-compare'
    | '/myt/post-tours'
    | '/myt/properties'
    | '/myt/schedule'
    | '/myt/score'
    | '/myt/settings'
    | '/myt/tcm'
    | '/myt/team'
    | '/myt/tours'
    | '/myt/war-room'
    | '/myt/zones'
    | '/property-owner/approvals'
    | '/property-owner/bookings'
    | '/property-owner/dashboard'
    | '/property-owner/inventory'
    | '/property-owner/notifications'
    | '/property-owner/profile'
    | '/property-owner/properties'
    | '/property-owner/visits'
    | '/supply-hub/$id'
    | '/supply-hub/areas'
    | '/supply-hub/match'
    | '/admin/'
    | '/myt/'
    | '/supply-hub/'
    | '/admin/agreements/$id'
    | '/admin/property-gallery/$id'
    | '/admin/tenants/$id'
    | '/myt/feedback/$id'
    | '/myt/tcm/actions'
    | '/myt/tcm/performance'
    | '/myt/tour/$id'
    | '/property-owner/properties/new'
    | '/admin/performance/flowops/$userId'
    | '/admin/performance/propertyowner/$userId'
    | '/admin/performance/tcm/$userId'
    | '/myt/tour/$id/report'
    | '/property-owner/properties/$id/rooms'
    | '/property-owner/properties/$id/rooms/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AdminRoute: typeof AdminRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  CoachRoute: typeof CoachRoute
  DailyProgressRoute: typeof DailyProgressRoute
  ExecutionRoute: typeof ExecutionRoute
  FollowUpsRoute: typeof FollowUpsRoute
  HandoffsRoute: typeof HandoffsRoute
  HealthRoute: typeof HealthRoute
  HeatmapRoute: typeof HeatmapRoute
  HelpRoute: typeof HelpRoute
  ImpactRoute: typeof ImpactRoute
  InboxRoute: typeof InboxRoute
  InventoryRoute: typeof InventoryRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LeadsRoute: typeof LeadsRouteWithChildren
  LiveLeadsRoute: typeof LiveLeadsRoute
  LoginRoute: typeof LoginRoute
  ManagerRoute: typeof ManagerRoute
  MyTasksRoute: typeof MyTasksRoute
  OwnerBookingsRoute: typeof OwnerBookingsRoute
  PropertyHubRoute: typeof PropertyHubRoute
  PropertyOwnerRoute: typeof PropertyOwnerRouteWithChildren
  QueueRoute: typeof QueueRoute
  RevenueRoute: typeof RevenueRoute
  RevivalRoute: typeof RevivalRoute
  SequencesRoute: typeof SequencesRoute
  SettingsRoute: typeof SettingsRoute
  TodayRoute: typeof TodayRoute
  ToursRoute: typeof ToursRoute
  VisitWarRoute: typeof VisitWarRoute
  ZoneBrainRoute: typeof ZoneBrainRoute
  ZonesRoute: typeof ZonesRoute
  MytBookingsRoute: typeof MytBookingsRoute
  MytCalendarRoute: typeof MytCalendarRoute
  MytDraftsRoute: typeof MytDraftsRoute
  MytFlowOpsRoute: typeof MytFlowOpsRoute
  MytFunnelRoute: typeof MytFunnelRoute
  MytInventoryFeedbackRoute: typeof MytInventoryFeedbackRoute
  MytLeaderboardRoute: typeof MytLeaderboardRoute
  MytLeadsRoute: typeof MytLeadsRoute
  MytMarketplaceRoute: typeof MytMarketplaceRoute
  MytMismatchRoute: typeof MytMismatchRoute
  MytOwnersCompareRoute: typeof MytOwnersCompareRoute
  MytPostToursRoute: typeof MytPostToursRoute
  MytPropertiesRoute: typeof MytPropertiesRoute
  MytScheduleRoute: typeof MytScheduleRoute
  MytScoreRoute: typeof MytScoreRoute
  MytSettingsRoute: typeof MytSettingsRoute
  MytTcmRoute: typeof MytTcmRouteWithChildren
  MytTeamRoute: typeof MytTeamRoute
  MytToursRoute: typeof MytToursRoute
  MytWarRoomRoute: typeof MytWarRoomRoute
  MytZonesRoute: typeof MytZonesRoute
  SupplyHubIdRoute: typeof SupplyHubIdRoute
  SupplyHubAreasRoute: typeof SupplyHubAreasRoute
  SupplyHubMatchRoute: typeof SupplyHubMatchRoute
  MytIndexRoute: typeof MytIndexRoute
  SupplyHubIndexRoute: typeof SupplyHubIndexRoute
  MytFeedbackIdRoute: typeof MytFeedbackIdRoute
  MytTourIdRoute: typeof MytTourIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zones': {
      id: '/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof ZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zone-brain': {
      id: '/zone-brain'
      path: '/zone-brain'
      fullPath: '/zone-brain'
      preLoaderRoute: typeof ZoneBrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit-war': {
      id: '/visit-war'
      path: '/visit-war'
      fullPath: '/visit-war'
      preLoaderRoute: typeof VisitWarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sequences': {
      id: '/sequences'
      path: '/sequences'
      fullPath: '/sequences'
      preLoaderRoute: typeof SequencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revival': {
      id: '/revival'
      path: '/revival'
      fullPath: '/revival'
      preLoaderRoute: typeof RevivalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-owner': {
      id: '/property-owner'
      path: '/property-owner'
      fullPath: '/property-owner'
      preLoaderRoute: typeof PropertyOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-hub': {
      id: '/property-hub'
      path: '/property-hub'
      fullPath: '/property-hub'
      preLoaderRoute: typeof PropertyHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner-bookings': {
      id: '/owner-bookings'
      path: '/owner-bookings'
      fullPath: '/owner-bookings'
      preLoaderRoute: typeof OwnerBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-tasks': {
      id: '/my-tasks'
      path: '/my-tasks'
      fullPath: '/my-tasks'
      preLoaderRoute: typeof MyTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-leads': {
      id: '/live-leads'
      path: '/live-leads'
      fullPath: '/live-leads'
      preLoaderRoute: typeof LiveLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatmap': {
      id: '/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof HeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoffs': {
      id: '/handoffs'
      path: '/handoffs'
      fullPath: '/handoffs'
      preLoaderRoute: typeof HandoffsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-ups': {
      id: '/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof FollowUpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/execution': {
      id: '/execution'
      path: '/execution'
      fullPath: '/execution'
      preLoaderRoute: typeof ExecutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-progress': {
      id: '/daily-progress'
      path: '/daily-progress'
      fullPath: '/daily-progress'
      preLoaderRoute: typeof DailyProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supply-hub/': {
      id: '/supply-hub/'
      path: '/supply-hub'
      fullPath: '/supply-hub/'
      preLoaderRoute: typeof SupplyHubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myt/': {
      id: '/myt/'
      path: '/myt'
      fullPath: '/myt/'
      preLoaderRoute: typeof MytIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/supply-hub/match': {
      id: '/supply-hub/match'
      path: '/supply-hub/match'
      fullPath: '/supply-hub/match'
      preLoaderRoute: typeof SupplyHubMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supply-hub/areas': {
      id: '/supply-hub/areas'
      path: '/supply-hub/areas'
      fullPath: '/supply-hub/areas'
      preLoaderRoute: typeof SupplyHubAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supply-hub/$id': {
      id: '/supply-hub/$id'
      path: '/supply-hub/$id'
      fullPath: '/supply-hub/$id'
      preLoaderRoute: typeof SupplyHubIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-owner/visits': {
      id: '/property-owner/visits'
      path: '/visits'
      fullPath: '/property-owner/visits'
      preLoaderRoute: typeof PropertyOwnerVisitsRouteImport
      parentRoute: typeof PropertyOwnerRoute
    }
    '/property-owner/properties': {
      id: '/property-owner/properties'
      path: '/properties'
      fullPath: '/property-owner/properties'
      preLoaderRoute: typeof PropertyOwnerPropertiesRouteImport
      parentRoute: typeof PropertyOwnerRoute
    }
    '/property-owner/profile': {
      id: '/property-owner/profile'
      path: '/profile'
      fullPath: '/property-owner/profile'
      preLoaderRoute: typeof PropertyOwnerProfileRouteImport
      parentRoute: typeof PropertyOwnerRoute
    }
    '/property-owner/notifications': {
      id: '/property-owner/notifications'
      path: '/notifications'
      fullPath: '/property-owner/notifications'
      preLoaderRoute: typeof PropertyOwnerNotificationsRouteImport
      parentRoute: typeof PropertyOwnerRoute
    }
    '/property-owner/inventory': {
      id: '/property-owner/inventory'
      path: '/inventory'
      fullPath: '/property-owner/inventory'
      preLoaderRoute: typeof PropertyOwnerInventoryRouteImport
      parentRoute: typeof PropertyOwnerRoute
    }
    '/property-owner/dashboard': {
      id: '/property-owner/dashboard'
      path: '/dashboard'
      fullPath: '/property-owner/dashboard'
      preLoaderRoute: typeof PropertyOwnerDashboardRouteImport
      parentRoute: typeof PropertyOwnerRoute
    }
    '/property-owner/bookings': {
      id: '/property-owner/bookings'
      path: '/bookings'
      fullPath: '/property-owner/bookings'
      preLoaderRoute: typeof PropertyOwnerBookingsRouteImport
      parentRoute: typeof PropertyOwnerRoute
    }
    '/property-owner/approvals': {
      id: '/property-owner/approvals'
      path: '/approvals'
      fullPath: '/property-owner/approvals'
      preLoaderRoute: typeof PropertyOwnerApprovalsRouteImport
      parentRoute: typeof PropertyOwnerRoute
    }
    '/myt/zones': {
      id: '/myt/zones'
      path: '/myt/zones'
      fullPath: '/myt/zones'
      preLoaderRoute: typeof MytZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myt/war-room': {
      id: '/myt/war-room'
      path: '/myt/war-room'
      fullPath: '/myt/war-room'
      preLoaderRoute: typeof MytWarRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myt/tours': {
      id: '/myt/tours'
      path: '/myt/tours'
      fullPath: '/myt/tours'
      preLoaderRoute: typeof MytToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myt/team': {
      id: '/myt/team'
      path: '/myt/team'
      fullPath: '/myt/team'
      preLoaderRoute: typeof MytTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myt/tcm': {
      id: '/myt/tcm'
      path: '/myt/tcm'
      fullPath: '/myt/tcm'
      preLoaderRoute: typeof MytTcmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myt/settings': {
      id: '/myt/settings'
      path: '/myt/settings'
      fullPath: '/myt/settings'
      preLoaderRoute: typeof MytSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myt/score': {
      id: '/myt/score'
      path: '/myt/score'
      fullPath: '/myt/score'
      preLoaderRoute: typeof MytScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myt/schedule': {
      id: '/myt/schedule'
      path: '/myt/schedule'
      fullPath: '/myt/schedule'
      preLoaderRoute: typeof MytScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myt/properties': {
      id: '/myt/properties'
      path: '/myt/properties'
      fullPath: '/myt/properties'
      preLoaderRoute: typeof MytPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myt/post-tours': {
      id: '/myt/post-tours'
      path: '/myt/post-tours'
      fullPath: '/myt/post-tours'
      preLoaderRoute: typeof MytPostToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myt/owners-compare': {
      id: '/myt/owners-compare'
      path: '/myt/owners-compare'
      fullPath: '/myt/owners-compare'
      preLoaderRoute: typeof MytOwnersCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myt/mismatch': {
      id: '/myt/mismatch'
      path: '/myt/mismatch'
      fullPath: '/myt/mismatch'
      preLoaderRoute: typeof MytMismatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myt/marketplace': {
      id: '/myt/marketplace'
      path: '/myt/marketplace'
      fullPath: '/myt/marketplace'
      preLoaderRoute: typeof MytMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myt/leads': {
      id: '/myt/leads'
      path: '/myt/leads'
      fullPath: '/myt/leads'
      preLoaderRoute: typeof MytLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myt/leaderboard': {
      id: '/myt/leaderboard'
      path: '/myt/leaderboard'
      fullPath: '/myt/leaderboard'
      preLoaderRoute: typeof MytLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myt/inventory-feedback': {
      id: '/myt/inventory-feedback'
      path: '/myt/inventory-feedback'
      fullPath: '/myt/inventory-feedback'
      preLoaderRoute: typeof MytInventoryFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myt/funnel': {
      id: '/myt/funnel'
      path: '/myt/funnel'
      fullPath: '/myt/funnel'
      preLoaderRoute: typeof MytFunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myt/flow-ops': {
      id: '/myt/flow-ops'
      path: '/myt/flow-ops'
      fullPath: '/myt/flow-ops'
      preLoaderRoute: typeof MytFlowOpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myt/drafts': {
      id: '/myt/drafts'
      path: '/myt/drafts'
      fullPath: '/myt/drafts'
      preLoaderRoute: typeof MytDraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myt/calendar': {
      id: '/myt/calendar'
      path: '/myt/calendar'
      fullPath: '/myt/calendar'
      preLoaderRoute: typeof MytCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myt/bookings': {
      id: '/myt/bookings'
      path: '/myt/bookings'
      fullPath: '/myt/bookings'
      preLoaderRoute: typeof MytBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/add': {
      id: '/leads/add'
      path: '/add'
      fullPath: '/leads/add'
      preLoaderRoute: typeof LeadsAddRouteImport
      parentRoute: typeof LeadsRoute
    }
    '/admin/whatsapp': {
      id: '/admin/whatsapp'
      path: '/whatsapp'
      fullPath: '/admin/whatsapp'
      preLoaderRoute: typeof AdminWhatsappRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/warroom': {
      id: '/admin/warroom'
      path: '/warroom'
      fullPath: '/admin/warroom'
      preLoaderRoute: typeof AdminWarroomRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/supreme': {
      id: '/admin/supreme'
      path: '/supreme'
      fullPath: '/admin/supreme'
      preLoaderRoute: typeof AdminSupremeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rents': {
      id: '/admin/rents'
      path: '/rents'
      fullPath: '/admin/rents'
      preLoaderRoute: typeof AdminRentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/radar': {
      id: '/admin/radar'
      path: '/radar'
      fullPath: '/admin/radar'
      preLoaderRoute: typeof AdminRadarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/property-gallery': {
      id: '/admin/property-gallery'
      path: '/property-gallery'
      fullPath: '/admin/property-gallery'
      preLoaderRoute: typeof AdminPropertyGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/property': {
      id: '/admin/property'
      path: '/property'
      fullPath: '/admin/property'
      preLoaderRoute: typeof AdminPropertyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/performance': {
      id: '/admin/performance'
      path: '/performance'
      fullPath: '/admin/performance'
      preLoaderRoute: typeof AdminPerformanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/people360': {
      id: '/admin/people360'
      path: '/people360'
      fullPath: '/admin/people360'
      preLoaderRoute: typeof AdminPeople360RouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/owners': {
      id: '/admin/owners'
      path: '/owners'
      fullPath: '/admin/owners'
      preLoaderRoute: typeof AdminOwnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/owner-bookings': {
      id: '/admin/owner-bookings'
      path: '/owner-bookings'
      fullPath: '/admin/owner-bookings'
      preLoaderRoute: typeof AdminOwnerBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leaderboard': {
      id: '/admin/leaderboard'
      path: '/leaderboard'
      fullPath: '/admin/leaderboard'
      preLoaderRoute: typeof AdminLeaderboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/intelligence': {
      id: '/admin/intelligence'
      path: '/intelligence'
      fullPath: '/admin/intelligence'
      preLoaderRoute: typeof AdminIntelligenceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/impact-command': {
      id: '/admin/impact-command'
      path: '/impact-command'
      fullPath: '/admin/impact-command'
      preLoaderRoute: typeof AdminImpactCommandRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/impact': {
      id: '/admin/impact'
      path: '/impact'
      fullPath: '/admin/impact'
      preLoaderRoute: typeof AdminImpactRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/health-score': {
      id: '/admin/health-score'
      path: '/health-score'
      fullPath: '/admin/health-score'
      preLoaderRoute: typeof AdminHealthScoreRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exports': {
      id: '/admin/exports'
      path: '/exports'
      fullPath: '/admin/exports'
      preLoaderRoute: typeof AdminExportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/execution-report': {
      id: '/admin/execution-report'
      path: '/execution-report'
      fullPath: '/admin/execution-report'
      preLoaderRoute: typeof AdminExecutionReportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/command': {
      id: '/admin/command'
      path: '/command'
      fullPath: '/admin/command'
      preLoaderRoute: typeof AdminCommandRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agreements': {
      id: '/admin/agreements'
      path: '/agreements'
      fullPath: '/admin/agreements'
      preLoaderRoute: typeof AdminAgreementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/property-owner/properties/new': {
      id: '/property-owner/properties/new'
      path: '/new'
      fullPath: '/property-owner/properties/new'
      preLoaderRoute: typeof PropertyOwnerPropertiesNewRouteImport
      parentRoute: typeof PropertyOwnerPropertiesRoute
    }
    '/myt/tour/$id': {
      id: '/myt/tour/$id'
      path: '/myt/tour/$id'
      fullPath: '/myt/tour/$id'
      preLoaderRoute: typeof MytTourIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myt/tcm/performance': {
      id: '/myt/tcm/performance'
      path: '/performance'
      fullPath: '/myt/tcm/performance'
      preLoaderRoute: typeof MytTcmPerformanceRouteImport
      parentRoute: typeof MytTcmRoute
    }
    '/myt/tcm/actions': {
      id: '/myt/tcm/actions'
      path: '/actions'
      fullPath: '/myt/tcm/actions'
      preLoaderRoute: typeof MytTcmActionsRouteImport
      parentRoute: typeof MytTcmRoute
    }
    '/myt/feedback/$id': {
      id: '/myt/feedback/$id'
      path: '/myt/feedback/$id'
      fullPath: '/myt/feedback/$id'
      preLoaderRoute: typeof MytFeedbackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tenants/$id': {
      id: '/admin/tenants/$id'
      path: '/$id'
      fullPath: '/admin/tenants/$id'
      preLoaderRoute: typeof AdminTenantsIdRouteImport
      parentRoute: typeof AdminTenantsRoute
    }
    '/admin/property-gallery/$id': {
      id: '/admin/property-gallery/$id'
      path: '/$id'
      fullPath: '/admin/property-gallery/$id'
      preLoaderRoute: typeof AdminPropertyGalleryIdRouteImport
      parentRoute: typeof AdminPropertyGalleryRoute
    }
    '/admin/agreements/$id': {
      id: '/admin/agreements/$id'
      path: '/$id'
      fullPath: '/admin/agreements/$id'
      preLoaderRoute: typeof AdminAgreementsIdRouteImport
      parentRoute: typeof AdminAgreementsRoute
    }
    '/property-owner/properties/$id/rooms': {
      id: '/property-owner/properties/$id/rooms'
      path: '/$id/rooms'
      fullPath: '/property-owner/properties/$id/rooms'
      preLoaderRoute: typeof PropertyOwnerPropertiesIdRoomsRouteImport
      parentRoute: typeof PropertyOwnerPropertiesRoute
    }
    '/myt/tour/$id/report': {
      id: '/myt/tour/$id/report'
      path: '/report'
      fullPath: '/myt/tour/$id/report'
      preLoaderRoute: typeof MytTourIdReportRouteImport
      parentRoute: typeof MytTourIdRoute
    }
    '/admin/performance/tcm/$userId': {
      id: '/admin/performance/tcm/$userId'
      path: '/tcm/$userId'
      fullPath: '/admin/performance/tcm/$userId'
      preLoaderRoute: typeof AdminPerformanceTcmUserIdRouteImport
      parentRoute: typeof AdminPerformanceRoute
    }
    '/admin/performance/propertyowner/$userId': {
      id: '/admin/performance/propertyowner/$userId'
      path: '/propertyowner/$userId'
      fullPath: '/admin/performance/propertyowner/$userId'
      preLoaderRoute: typeof AdminPerformancePropertyownerUserIdRouteImport
      parentRoute: typeof AdminPerformanceRoute
    }
    '/admin/performance/flowops/$userId': {
      id: '/admin/performance/flowops/$userId'
      path: '/flowops/$userId'
      fullPath: '/admin/performance/flowops/$userId'
      preLoaderRoute: typeof AdminPerformanceFlowopsUserIdRouteImport
      parentRoute: typeof AdminPerformanceRoute
    }
    '/property-owner/properties/$id/rooms/$roomId': {
      id: '/property-owner/properties/$id/rooms/$roomId'
      path: '/$roomId'
      fullPath: '/property-owner/properties/$id/rooms/$roomId'
      preLoaderRoute: typeof PropertyOwnerPropertiesIdRoomsRoomIdRouteImport
      parentRoute: typeof PropertyOwnerPropertiesIdRoomsRoute
    }
  }
}

interface AdminAgreementsRouteChildren {
  AdminAgreementsIdRoute: typeof AdminAgreementsIdRoute
}

const AdminAgreementsRouteChildren: AdminAgreementsRouteChildren = {
  AdminAgreementsIdRoute: AdminAgreementsIdRoute,
}

const AdminAgreementsRouteWithChildren = AdminAgreementsRoute._addFileChildren(
  AdminAgreementsRouteChildren,
)

interface AdminPerformanceRouteChildren {
  AdminPerformanceFlowopsUserIdRoute: typeof AdminPerformanceFlowopsUserIdRoute
  AdminPerformancePropertyownerUserIdRoute: typeof AdminPerformancePropertyownerUserIdRoute
  AdminPerformanceTcmUserIdRoute: typeof AdminPerformanceTcmUserIdRoute
}

const AdminPerformanceRouteChildren: AdminPerformanceRouteChildren = {
  AdminPerformanceFlowopsUserIdRoute: AdminPerformanceFlowopsUserIdRoute,
  AdminPerformancePropertyownerUserIdRoute:
    AdminPerformancePropertyownerUserIdRoute,
  AdminPerformanceTcmUserIdRoute: AdminPerformanceTcmUserIdRoute,
}

const AdminPerformanceRouteWithChildren =
  AdminPerformanceRoute._addFileChildren(AdminPerformanceRouteChildren)

interface AdminPropertyGalleryRouteChildren {
  AdminPropertyGalleryIdRoute: typeof AdminPropertyGalleryIdRoute
}

const AdminPropertyGalleryRouteChildren: AdminPropertyGalleryRouteChildren = {
  AdminPropertyGalleryIdRoute: AdminPropertyGalleryIdRoute,
}

const AdminPropertyGalleryRouteWithChildren =
  AdminPropertyGalleryRoute._addFileChildren(AdminPropertyGalleryRouteChildren)

interface AdminTenantsRouteChildren {
  AdminTenantsIdRoute: typeof AdminTenantsIdRoute
}

const AdminTenantsRouteChildren: AdminTenantsRouteChildren = {
  AdminTenantsIdRoute: AdminTenantsIdRoute,
}

const AdminTenantsRouteWithChildren = AdminTenantsRoute._addFileChildren(
  AdminTenantsRouteChildren,
)

interface AdminRouteChildren {
  AdminAgreementsRoute: typeof AdminAgreementsRouteWithChildren
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminCommandRoute: typeof AdminCommandRoute
  AdminExecutionReportRoute: typeof AdminExecutionReportRoute
  AdminExportsRoute: typeof AdminExportsRoute
  AdminHealthScoreRoute: typeof AdminHealthScoreRoute
  AdminImpactRoute: typeof AdminImpactRoute
  AdminImpactCommandRoute: typeof AdminImpactCommandRoute
  AdminIntelligenceRoute: typeof AdminIntelligenceRoute
  AdminLeaderboardRoute: typeof AdminLeaderboardRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminOwnerBookingsRoute: typeof AdminOwnerBookingsRoute
  AdminOwnersRoute: typeof AdminOwnersRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminPeople360Route: typeof AdminPeople360Route
  AdminPerformanceRoute: typeof AdminPerformanceRouteWithChildren
  AdminPropertyRoute: typeof AdminPropertyRoute
  AdminPropertyGalleryRoute: typeof AdminPropertyGalleryRouteWithChildren
  AdminRadarRoute: typeof AdminRadarRoute
  AdminRentsRoute: typeof AdminRentsRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupremeRoute: typeof AdminSupremeRoute
  AdminTenantsRoute: typeof AdminTenantsRouteWithChildren
  AdminWarroomRoute: typeof AdminWarroomRoute
  AdminWhatsappRoute: typeof AdminWhatsappRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgreementsRoute: AdminAgreementsRouteWithChildren,
  AdminAuditRoute: AdminAuditRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminCommandRoute: AdminCommandRoute,
  AdminExecutionReportRoute: AdminExecutionReportRoute,
  AdminExportsRoute: AdminExportsRoute,
  AdminHealthScoreRoute: AdminHealthScoreRoute,
  AdminImpactRoute: AdminImpactRoute,
  AdminImpactCommandRoute: AdminImpactCommandRoute,
  AdminIntelligenceRoute: AdminIntelligenceRoute,
  AdminLeaderboardRoute: AdminLeaderboardRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminOwnerBookingsRoute: AdminOwnerBookingsRoute,
  AdminOwnersRoute: AdminOwnersRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminPeople360Route: AdminPeople360Route,
  AdminPerformanceRoute: AdminPerformanceRouteWithChildren,
  AdminPropertyRoute: AdminPropertyRoute,
  AdminPropertyGalleryRoute: AdminPropertyGalleryRouteWithChildren,
  AdminRadarRoute: AdminRadarRoute,
  AdminRentsRoute: AdminRentsRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupremeRoute: AdminSupremeRoute,
  AdminTenantsRoute: AdminTenantsRouteWithChildren,
  AdminWarroomRoute: AdminWarroomRoute,
  AdminWhatsappRoute: AdminWhatsappRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LeadsRouteChildren {
  LeadsAddRoute: typeof LeadsAddRoute
}

const LeadsRouteChildren: LeadsRouteChildren = {
  LeadsAddRoute: LeadsAddRoute,
}

const LeadsRouteWithChildren = LeadsRoute._addFileChildren(LeadsRouteChildren)

interface PropertyOwnerPropertiesIdRoomsRouteChildren {
  PropertyOwnerPropertiesIdRoomsRoomIdRoute: typeof PropertyOwnerPropertiesIdRoomsRoomIdRoute
}

const PropertyOwnerPropertiesIdRoomsRouteChildren: PropertyOwnerPropertiesIdRoomsRouteChildren =
  {
    PropertyOwnerPropertiesIdRoomsRoomIdRoute:
      PropertyOwnerPropertiesIdRoomsRoomIdRoute,
  }

const PropertyOwnerPropertiesIdRoomsRouteWithChildren =
  PropertyOwnerPropertiesIdRoomsRoute._addFileChildren(
    PropertyOwnerPropertiesIdRoomsRouteChildren,
  )

interface PropertyOwnerPropertiesRouteChildren {
  PropertyOwnerPropertiesNewRoute: typeof PropertyOwnerPropertiesNewRoute
  PropertyOwnerPropertiesIdRoomsRoute: typeof PropertyOwnerPropertiesIdRoomsRouteWithChildren
}

const PropertyOwnerPropertiesRouteChildren: PropertyOwnerPropertiesRouteChildren =
  {
    PropertyOwnerPropertiesNewRoute: PropertyOwnerPropertiesNewRoute,
    PropertyOwnerPropertiesIdRoomsRoute:
      PropertyOwnerPropertiesIdRoomsRouteWithChildren,
  }

const PropertyOwnerPropertiesRouteWithChildren =
  PropertyOwnerPropertiesRoute._addFileChildren(
    PropertyOwnerPropertiesRouteChildren,
  )

interface PropertyOwnerRouteChildren {
  PropertyOwnerApprovalsRoute: typeof PropertyOwnerApprovalsRoute
  PropertyOwnerBookingsRoute: typeof PropertyOwnerBookingsRoute
  PropertyOwnerDashboardRoute: typeof PropertyOwnerDashboardRoute
  PropertyOwnerInventoryRoute: typeof PropertyOwnerInventoryRoute
  PropertyOwnerNotificationsRoute: typeof PropertyOwnerNotificationsRoute
  PropertyOwnerProfileRoute: typeof PropertyOwnerProfileRoute
  PropertyOwnerPropertiesRoute: typeof PropertyOwnerPropertiesRouteWithChildren
  PropertyOwnerVisitsRoute: typeof PropertyOwnerVisitsRoute
}

const PropertyOwnerRouteChildren: PropertyOwnerRouteChildren = {
  PropertyOwnerApprovalsRoute: PropertyOwnerApprovalsRoute,
  PropertyOwnerBookingsRoute: PropertyOwnerBookingsRoute,
  PropertyOwnerDashboardRoute: PropertyOwnerDashboardRoute,
  PropertyOwnerInventoryRoute: PropertyOwnerInventoryRoute,
  PropertyOwnerNotificationsRoute: PropertyOwnerNotificationsRoute,
  PropertyOwnerProfileRoute: PropertyOwnerProfileRoute,
  PropertyOwnerPropertiesRoute: PropertyOwnerPropertiesRouteWithChildren,
  PropertyOwnerVisitsRoute: PropertyOwnerVisitsRoute,
}

const PropertyOwnerRouteWithChildren = PropertyOwnerRoute._addFileChildren(
  PropertyOwnerRouteChildren,
)

interface MytTcmRouteChildren {
  MytTcmActionsRoute: typeof MytTcmActionsRoute
  MytTcmPerformanceRoute: typeof MytTcmPerformanceRoute
}

const MytTcmRouteChildren: MytTcmRouteChildren = {
  MytTcmActionsRoute: MytTcmActionsRoute,
  MytTcmPerformanceRoute: MytTcmPerformanceRoute,
}

const MytTcmRouteWithChildren =
  MytTcmRoute._addFileChildren(MytTcmRouteChildren)

interface MytTourIdRouteChildren {
  MytTourIdReportRoute: typeof MytTourIdReportRoute
}

const MytTourIdRouteChildren: MytTourIdRouteChildren = {
  MytTourIdReportRoute: MytTourIdReportRoute,
}

const MytTourIdRouteWithChildren = MytTourIdRoute._addFileChildren(
  MytTourIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AdminRoute: AdminRouteWithChildren,
  CalendarRoute: CalendarRoute,
  CoachRoute: CoachRoute,
  DailyProgressRoute: DailyProgressRoute,
  ExecutionRoute: ExecutionRoute,
  FollowUpsRoute: FollowUpsRoute,
  HandoffsRoute: HandoffsRoute,
  HealthRoute: HealthRoute,
  HeatmapRoute: HeatmapRoute,
  HelpRoute: HelpRoute,
  ImpactRoute: ImpactRoute,
  InboxRoute: InboxRoute,
  InventoryRoute: InventoryRoute,
  LeaderboardRoute: LeaderboardRoute,
  LeadsRoute: LeadsRouteWithChildren,
  LiveLeadsRoute: LiveLeadsRoute,
  LoginRoute: LoginRoute,
  ManagerRoute: ManagerRoute,
  MyTasksRoute: MyTasksRoute,
  OwnerBookingsRoute: OwnerBookingsRoute,
  PropertyHubRoute: PropertyHubRoute,
  PropertyOwnerRoute: PropertyOwnerRouteWithChildren,
  QueueRoute: QueueRoute,
  RevenueRoute: RevenueRoute,
  RevivalRoute: RevivalRoute,
  SequencesRoute: SequencesRoute,
  SettingsRoute: SettingsRoute,
  TodayRoute: TodayRoute,
  ToursRoute: ToursRoute,
  VisitWarRoute: VisitWarRoute,
  ZoneBrainRoute: ZoneBrainRoute,
  ZonesRoute: ZonesRoute,
  MytBookingsRoute: MytBookingsRoute,
  MytCalendarRoute: MytCalendarRoute,
  MytDraftsRoute: MytDraftsRoute,
  MytFlowOpsRoute: MytFlowOpsRoute,
  MytFunnelRoute: MytFunnelRoute,
  MytInventoryFeedbackRoute: MytInventoryFeedbackRoute,
  MytLeaderboardRoute: MytLeaderboardRoute,
  MytLeadsRoute: MytLeadsRoute,
  MytMarketplaceRoute: MytMarketplaceRoute,
  MytMismatchRoute: MytMismatchRoute,
  MytOwnersCompareRoute: MytOwnersCompareRoute,
  MytPostToursRoute: MytPostToursRoute,
  MytPropertiesRoute: MytPropertiesRoute,
  MytScheduleRoute: MytScheduleRoute,
  MytScoreRoute: MytScoreRoute,
  MytSettingsRoute: MytSettingsRoute,
  MytTcmRoute: MytTcmRouteWithChildren,
  MytTeamRoute: MytTeamRoute,
  MytToursRoute: MytToursRoute,
  MytWarRoomRoute: MytWarRoomRoute,
  MytZonesRoute: MytZonesRoute,
  SupplyHubIdRoute: SupplyHubIdRoute,
  SupplyHubAreasRoute: SupplyHubAreasRoute,
  SupplyHubMatchRoute: SupplyHubMatchRoute,
  MytIndexRoute: MytIndexRoute,
  SupplyHubIndexRoute: SupplyHubIndexRoute,
  MytFeedbackIdRoute: MytFeedbackIdRoute,
  MytTourIdRoute: MytTourIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
